#!/bin/sh
set -e

psql -l

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE TABLE house_prices (
        id            integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        property_type varchar(100),
        price         integer,
        location      varchar(400),
        city          varchar(400),
        baths         integer,
        purpose       varchar(100),
        bedrooms      integer,
        area_in_marla float8
    );
    COPY house_prices(id, property_type, price, location, city, baths, purpose, bedrooms, area_in_marla)
    FROM '/raw/house_prices.csv'
    DELIMITER ','
    CSV HEADER;
    select * from house_prices limit 5;
EOSQL